version: "3.8"
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "${APP_PORT-3000}:80"
    volumes:
      - .:/usr/src/app
    command: air cmd/main.go -b 0.0.0.0
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT_FORWARD}:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
